### ISSUE TITLE
Kevin Clough talk text is incorrect

### ISSUE THREAD

**Issue by KClough** [LibertyJS/libertyjs.github.io-dev#21]
Looks like it was copy pasted from Warren Longmire's talk.

**Comment by pselle** [comment]
Q: Is Tim also a speaker, @KClough

**Comment by KClough** [comment]
Naw, Tim declined, but Lauren Ancona is interested in presenting with me.

**Comment by pselle** [comment]
Updated http://libertyjs.com/#/speakers

**Comment by pselle** [comment]
@KClough Cool, just let @belcherj know so he can get things updated if so

**Comment by KClough** [comment]
Yea, she will definitely be presenting with me.
